apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ousg8gc9m-go 
  janus-idp.io/tekton: ousg8gc9m-go
  backstage.io/kubernetes-id: ousg8gc9m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ousg8gc9m-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml