apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ousg8gc9m-go-gitops
  description: This is GitOps manifest for ousg8gc9m-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ousg8gc9m-go
    backstage.io/kubernetes-id: ousg8gc9m-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: ousg8gc9m-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ousg8gc9m-go
